### ISSUE TITLE
Strange error "free(): invalid pointer"

### ISSUE THREAD

**Issue by remicollet** [jbboehr/php-mustache#35]
Trying to build this extension for RHEL-7

Using default compiler (gcc 4.8) works for PHP 5.6 to 7.1

But with PHP 7.2 (build with gcc 6.2) this doesn't work

```
/opt/remi/php72/root/usr/include/php/Zend/zend_operators.h: In function 'void fast_long_increment_function(zval*)':
/opt/remi/php72/root/usr/include/php/Zend/zend_operators.h:446:68: error: '__builtin_saddl_overflow' was not declared in this scope
  if (UNEXPECTED(__builtin_saddl_overflow(Z_LVAL_P(op1), 1, &lresult))) {
```

So switch to gcc 6.2... (which also need pr #34) and the strange error appears (all PHP versions)

```
========DIFF========
001+ *** Error in `/opt/remi/php71/root/usr/bin/php': free(): invalid pointer: 0x000055b65f1cd788 ***
001- __FILE__\s*\!\=\s*__LINE__
002+ ======= Backtrace: =========
003+ /lib64/libc.so.6(+0x7c503)[0x7ff9ac865503]
004+ /lib64/libmustache.so.4(_ZN8mustache4DataD1Ev+0x60)[0x7ff9aafdaaf0]
005+ /lib64/libmustache.so.4(_ZN8mustache4DataD1Ev+0x189)[0x7ff9aafdac19]
006+ /builddir/build/BUILD/php71-php-pecl-mustache-0.7.4~RC1/NTS/modules/mustache.so(zim_Mustache_render+0x3c1)[0x7ff9ab1f6f91]
007+ /opt/remi/php71/root/usr/bin/php(+0x344194)[0x55b65ea0f194]
008+ /opt/remi/php71/root/usr/bin/php(execute_ex+0x2b)[0x55b65e9b5e7b]
009+ /opt/remi/php71/root/usr/bin/php(zend_execute+0x188)[0x55b65ea115f8]
010+ /opt/remi/php71/root/usr/bin/php(zend_execute_scripts+0xd3)[0x55b65e96c183]
011+ /opt/remi/php71/root/usr/bin/php(php_execute_script+0x2d0)[0x55b65e908050]
012+ /opt/remi/php71/root/usr/bin/php(+0x34885c)[0x55b65ea1385c]
013+ /opt/remi/php71/root/usr/bin/php(+0xcdcba)[0x55b65e798cba]
014+ /lib64/libc.so.6(__libc_start_main+0xf5)[0x7ff9ac80ab35]
015+ /opt/remi/php71/root/usr/bin/php(+0xcddd6)[0x55b65e798dd6]
```

/me going crazy....

**Comment by jbboehr** [comment]
@remicollet I notice I have that error if libmustache is compiled with gcc 4.8, but php-mustache is compiled with gcc 6.2:

```
FROM centos:7

RUN rm -f /var/lib/rpm/__* && rpm --rebuilddb -v -v && yum clean all
RUN sed -i s/enabled=1/enabled=0/g /etc/yum/pluginconf.d/fastestmirror.conf
RUN yum install -y centos-release-scl
RUN yum install -y yum install devtoolset-6-gcc*
RUN yum install -y php php-devel autoconf automake libtool make m4 git file
RUN yum install -y gcc gcc-c++

RUN gcc --version && \
	git clone https://github.com/jbboehr/libmustache.git /libmustache && \
	cd /libmustache && \
	autoreconf -fiv && \
	./configure --without-mustache-spec && \
	make clean all install

RUN source scl_source enable devtoolset-6 && \
	gcc --version && \
	git clone https://github.com/jbboehr/php-mustache.git /php-mustache && \
	cd /php-mustache && \
	phpize && \
	./configure --enable-mustache && \
	make clean all

RUN echo "source scl_source enable devtoolset-6 && cd /php-mustache && make test" > /entry.sh && \
	chmod +x /entry.sh

CMD "bash" "/entry.sh"
```

vs

```
FROM centos:7

RUN rm -f /var/lib/rpm/__* && rpm --rebuilddb -v -v && yum clean all
RUN sed -i s/enabled=1/enabled=0/g /etc/yum/pluginconf.d/fastestmirror.conf
RUN yum install -y centos-release-scl
RUN yum install -y yum install devtoolset-6-gcc*
RUN yum install -y php php-devel autoconf automake libtool make m4 git file

RUN source scl_source enable devtoolset-6 && \
	gcc --version && \
	git clone https://github.com/jbboehr/libmustache.git /libmustache && \
	cd /libmustache && \
	autoreconf -fiv && \
	./configure --without-mustache-spec && \
	make clean all install

RUN source scl_source enable devtoolset-6 && \
	gcc --version && \
	git clone https://github.com/jbboehr/php-mustache.git /php-mustache && \
	cd /php-mustache && \
	phpize && \
	./configure --enable-mustache && \
	make clean all

RUN echo "source scl_source enable devtoolset-6 && cd /php-mustache && make test" > /entry.sh && \
	chmod +x /entry.sh

CMD "bash" "/entry.sh"
```

**Comment by jbboehr** [comment]
I assume there is some issue with usage of `std::unordered_map` in the library vs extension being compiled under different versions of gcc.

**Comment by jbboehr** [comment]
@remicollet let me know if compiling libmustache and php-mustache with the same version of gcc works for you, and whether or not it's possible to do that for your packaging needs.

I believe ensuring an object is both created and destroyed in code compiled by a particular version of gcc (meaning an object created in `php-mustache` would need to also be destroyed in `php-mustache`), might be a possible workaround, but it seems dangerous using two different versions to compile parts of the code.

**Comment by remicollet** [comment]
> whether or not it's possible to do that for your packaging needs.

The issue is that only php 7.1/7.2 are built with gcc 6.2 (which give some perf improvement)
So changing gcc version used for libmustaphe will result in other issue for 5.6/7.0

**Comment by remicollet** [comment]
Ok, using GCC 6.2 for both libmustache and pecl/mustache fixes the issue (build + test sutie ok with PHP 5.6/7.0/7.1/7.2)

So fixed on my side by
* https://git.remirepo.net/cgit/rpms/lib/libmustache.git/commit/?id=18e92a27903816b6db19122eb03ddcfb8c29afdd
* https://git.remirepo.net/cgit/rpms/lib/libmustache.git/commit/?id=18e92a27903816b6db19122eb03ddcfb8c29afdd

Closing as very specific to build environment

**Comment by jbboehr** [comment]
Perfect!
