### PR TITLE
Fix build with PHP 7.4

### PR DESCRIPTION
**Pull request by sunpoet**
Build error on FreeBSD with PHP 7.4 RC6:
```
--- mustache_mustache.lo ---
/wrkdirs/usr/ports/devel/pecl-mustache/work-php74/mustache-0.9.0/mustache_mustache.cpp:234:5: error: unknown type name 'ulong'
    ulong key_nindex = 0;
    ^
1 error generated.
*** [mustache_mustache.lo] Error code 1
```
```
--- mustache_data.lo ---
/wrkdirs/usr/ports/devel/pecl-mustache/work-php74/mustache-0.9.0/mustache_data.cpp:139:3: error: unknown type name 'ulong'
  ulong key_nindex = 0;
  ^
/wrkdirs/usr/ports/devel/pecl-mustache/work-php74/mustache-0.9.0/mustache_data.cpp:231:3: error: unknown type name 'ulong'
  ulong key_nindex = 0;
  ^
/wrkdirs/usr/ports/devel/pecl-mustache/work-php74/mustache-0.9.0/mustache_data.cpp:278:32: warning: comparison of address of 'ce->properties_info' not equal to a null pointer is always true [-Wtautological-pointer-compare]
        if( ce != NULL && &ce->properties_info != NULL ) {
                           ~~~~^~~~~~~~~~~~~~~    ~~~~
/wrkdirs/usr/ports/devel/pecl-mustache/work-php74/mustache-0.9.0/mustache_data.cpp:314:3: error: unknown type name 'ulong'
  ulong key_nindex = 0;
  ^
1 warning and 3 errors generated.
*** [mustache_data.lo] Error code 1
```

### CODE REVIEW

**Comment by jbboehr** [comment]
LGTM, thanks!
